### ISSUE TITLE
Keysy option not taken into account and Gerudo Valley checks not turning green when getting Auru's Memo

### ISSUE THREAD

**Issue by laurentdupin** [AudioPixie/TPRTracker#29] opened 2024-01-17 21:57 UTC
Hello, 

I have been playing using this tracker and really enjoyed using it.
But I encountered 2 issues that have been distracting:

- The keysy option seems to not be taken into account, I need to manually set every dungeon keys to their maximum for the expected checks to be unlocked
- During my run with this seed ([Tpr--LivelyBeth_7mc--SpoilerLog-Q0_clG9xLSI.json](https://github.com/AudioPixie/TPRTracker/files/13969068/Tpr--LivelyBeth_7mc--SpoilerLog-Q0_clG9xLSI.json)), at sphere 4 I am expected to go to Gerudo Valley but somehow the tracker does not turn the Gerudo Valley checks green when inputing the objects from the first 4 spheres. Auru's memo was a big hint towards that so I went anyway but that felt weird and it seems that outside the Shadow crystal nothing enables those checks.

Also, I used the Import Log option in the case that is an issue related to that feature and the build is from the 1/08/2024.

Have a nice day!

**Comment by AudioPixie** [comment] 2024-01-18 02:34
Hey, thanks for letting me know! Jsyk,

- Use "Ignore Key Logic" in general settings for now to achieve that effect, this will be changed soon, the keysy setting was added as a quick fix for gate key logic, but I'll be changing how those settings work pretty soon. Going to look into why the setting wasn't enabled automatically when you imported as I think it's supposed to be, thanks for attaching the log!
- For desert, rn shadow crystal is required for access, I think this is a leftover of old logic (you needed to be able to warp out of desert, but I believe now if you save warp you end up back in lake hylia so you don't need crystal). It's going to be fixed along with a bunch of other stuff as there's a big logic update coming

**Comment by AudioPixie** [comment] 2024-01-18 23:17
FYI looked into it and the reason Ignore Key Logic wasn't checked automatically on import is because the big key settings weren't keysy, it only checks it if both are. Working as intended but that whole system is on the chopping block rn and won't be a thing soon anyway

**Comment by AudioPixie** [comment] 2024-01-20 09:24
Fixed with upcoming logic update!

**Closed by AudioPixie** 2024-01-20 09:24 UTC
Labels: bug, High priority
